--- 
kafka: 
  bootstrap-servers: "34.205.236.80:9092"
  consumergroup: requestreplygroup
  topic: 
    request-topic: request-topic
    requestreply-topic: requestreply-topic
server: 
  port: 8080
spring: 
  application: 
    name: request_reply_kafka
